version: '2'
services:
  kulonga-app:
    image: kulonga
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kulonga-postgresql:5432/kulonga
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://kulonga-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://kulonga-elasticsearch:9200
    ports:
      - 8080:8080
  kulonga-postgresql:
    extends:
      file: postgresql.yml
      service: kulonga-postgresql
  kulonga-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: kulonga-elasticsearch
